IIP-Design/content-commons-client

components/admin/Upload/ContentModals/VideoUpload/VideoProjectType/VideoProjectType.js, components/admin/Upload/ContentModals/VideoUpload/VideoProjectType/VideoProjectType.scss, components/admin/Upload/ContentModals/VideoUpload/VideoUpload.js, components/admin/Upload/ContentModals/VideoUpload/VideoUpload.scss, components/admin/Upload/Upload.js, components/admin/Upload/Upload.scss, package-lock.json
- UI for first screen of video upload -- "What type of video project is this?"
- includes text updates to Upload page (CDP-1135)
=> CDP-1134 - Video Upload Modal Screens

.eslintrc, components/ScrollableTableWithMenu/TableBody/index.js, components/ScrollableTableWithMenu/index.js, components/admin/Dashboard/MyProjects/DetailsPopup/DetailsPopup.js, components/admin/Dashboard/MyProjects/MyProjectPrimaryCol/index.js, components/admin/Dashboard/MyProjects/PreviewProjectItem.js, components/admin/Dashboard/MyProjects/ShareProjectItem/ShareProjectItem.js, components/admin/Dashboard/MyProjects/ShareProjectItem/ShareProjectItem.scss, components/modals/ModalItem/ModalItem.scss
- branched off of Dashboard_Base
- per UX, Share popup provides project review link
=> CDP-1280 - Dashboard Project Share Popup

components/ScrollableTableWithMenu/ScrollableTableWithMenu.scss, components/ScrollableTableWithMenu/TableItemsDisplay/index.js, components/ScrollableTableWithMenu/TableMenu/TableMenu.scss, components/ScrollableTableWithMenu/TableMenu/index.js, components/ScrollableTableWithMenu/index.js
Adds keyboard accessibility to the dashboard Show More dropdown and table scroll arrows
=> CDP-1314: Show More dropdown keyboard accessibility

components/admin/dropdowns/LanguageDropdown.js, components/admin/dropdowns/QualityDropdown.js, components/admin/dropdowns/UseDropdown.js, components/admin/dropdowns/VideoBurnedInStatusDropdown.js, lib/utils.js
Added util function for adding an empty option object to the beginning of an option array.
Updated upload dropdowns to prepend empty option to each option array.
=> CDP-1287: Blanks are missing from Language, Type/Use, Quality and Subtitle dropdown list

components/admin/Dashboard/MyProjects/DetailsPopup/VideoDetailsPopup.js, components/admin/Dashboard/MyProjects/PreviewProjectItem.js, components/admin/projects/ProjectEdit/PreviewProjectContent/PreviewProjectContent.js, components/admin/projects/ProjectEdit/PreviewProjectContent/PreviewProjectContent.scss, lib/utils.js
- includes adjustments to video review and preview queries to address loading errors
- also includes several items carried over from the last merge, i.e., DownloadSrt, DownloadThumbnail, DownloadOtherFiles, util fns
=> Video review fixes

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js, components/ScrollableTableWithMenu/TableActionsMenu/DeleteIconButton/DeleteIconButton.js, components/ScrollableTableWithMenu/TableActionsMenu/DeleteIconButton/DeleteIconButton.test.js, components/ScrollableTableWithMenu/TableActionsMenu/DeleteProjects/DeleteProjects.js, components/ScrollableTableWithMenu/TableActionsMenu/DeleteProjects/DeleteProjects.test.js, components/ScrollableTableWithMenu/TableActionsMenu/DeleteProjects/__snapshots__/DeleteProjects.test.js.snap, components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.js, components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.test.js, components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js, components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.test.js, components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/__snapshots__/UnpublishProjects.test.js.snap, components/ScrollableTableWithMenu/TableBody/TableBody.test.js, components/ScrollableTableWithMenu/TableMenu/TableMenu.js, components/ScrollableTableWithMenu/TableMenu/TableMenu.test.js, components/ScrollableTableWithMenu/TableMenu/__snapshots__/TableMenu.test.js.snap, components/ScrollableTableWithMenu/TablePagination/TablePagination.js, components/ScrollableTableWithMenu/TableRow/TableRow.js, components/ScrollableTableWithMenu/TableRow/TableRow.test.js, components/ScrollableTableWithMenu/TableRow/__snapshots__/TableRow.test.js.snap
* Unpublish button is hidden if all selected projects are drafts
* Unpublish button is *not* hidden if at least one selected project is *not* a draft
=> CDP-1331: Hide Unpublish button if all draft projects selected

components/ScrollableTableWithMenu/ScrollableTableWithMenu.scss, components/ScrollableTableWithMenu/TableBody/TableBody.js, components/ScrollableTableWithMenu/TableItemsDisplay/TableItemsDisplay.test.js, components/ScrollableTableWithMenu/TablePagination/TablePagination.js
Visiting the dashboard after uploading a project displays that project in the list
=> CDP-1329: Dashboard Refreshing

components/admin/ConfirmModalContent/ConfirmModalContent.scss, components/admin/Upload/modals/RemoveFile/RemoveFile.js, components/admin/Upload/modals/VideoUpload/VideoUpload.js
Added RemoveFile confirmation modal for the prepare file upload process.
Updated ConfirmModalContent CSS to include overrides for the remove-file class.
=> CDP-1306: Remove File modal for upload preparation process

components/admin/projects/ProjectReview/VideoReview/VideoReview.js, lib/graphql/queries/video.js
Created mutation for publish video project.
Added mutation call to the publish button handler.
=> CDP-1358: Connect Publish Button

components/admin/projects/ProjectEdit/EditSingleProjectItem/EditSingleProjectItem.js, components/admin/projects/ProjectEdit/EditVideoModal/Carousel/Carousel.js, components/admin/projects/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js, components/admin/projects/ProjectEdit/EditVideoModal/ModalSections/FileSection/FileSection.js, components/admin/projects/ProjectEdit/EditVideoModal/ModalSections/FileSidebar/FileSidebar.js, components/admin/projects/ProjectEdit/EditVideoModal/ModalSections/VideoUnitCarousel/VideoUnitCarousel.js
Takes advantage of the useEffect to trigger the language mutations when the language state is updated.
Also cleans up the modal context by eliminating some unused functions.
=> CDP-1383: Fix language switcher in Edit Video Modal

components/Register/Register.js, components/Register/UserDetails/UserDetails.js, components/Register/UserDetails/validationSchema.js
Wrapped Register component in withApollo in order to use Apollo client to query whitelist.
Modified UserDetails validationSchema to use isWhitelisted prop from Register in the email validation.
=> CDP-1460: Email Whitelist

components/admin/ProjectEdit/EditVideoModal/ModalForms/UnitDataForm/UnitDataForm.js, components/admin/dropdowns/CategoryDropdown.js, components/admin/dropdowns/TagDropdown.js, components/admin/dropdowns/dropdown.scss
Add a filter by locale to tag query in tag dropdown
=> Only pull in tags from specified locale

components/admin/ProjectEdit/ProjectPreviewContent/ProjectPreviewContent.js, components/admin/ProjectEdit/ProjectPreviewContent/ProjectPreviewContent.test.js, components/admin/ProjectEdit/ProjectPreviewContent/__snapshots__/ProjectPreviewContent.test.js.snap, components/admin/ProjectEdit/ProjectPreviewContent/mocks.js
* adjust handling of short YouTube urls to display embed icon
* use signedUrl for video thumbnailUrl
* adjust tests as needed
=> Embed icon fix

components/admin/PackageEdit/PackageDetailsFormContainer/validationSchema.js, components/admin/PackageEdit/PackageFiles/PressPackageFile/PressPackageFile.js, components/admin/dropdowns/UseDropdown/UseDropdown.test.js, lib/graphql/builders/package.js
* Adjust Package Details form validation schema to handle dynamic fields
* Update test setup for UseDropdown
=> CDP-1615 - Package Details Form validation schema handles dynamic fields

components/admin/PackagePreview/PressPackageItem/PressPackageItem.scss
* Reset CSS position property for document card meta footer
=> CDP-1574 - Build Package Preview Modal

components/Share/Share.js, components/Share/Share.test.js
* Hide social media links for package type
* Updated tests for Share component
=> CDP-1664 - Hide social media links for package type

components/Share/Share.js, components/Share/Share.test.js, components/Share/__snapshots__/Share.test.js.snap
* Adjust Share on Twitter link to use Twitter web intents
* Update tests for Share component
=> CDP-1698 - Fix Share on Twitter link

components/Package/PressPackageItem/PressPackageItem.js, components/Package/PressPackageItem/PressPackageItem.scss, components/Package/PressPackageItem/PressPackageItem.test.js, components/Package/utils.js, lib/graphql/queries/document.js
* Use excerpt provided by servers instead of calculating excerpt on client
* Update tests for PressPackageItem
=> CDP-1718 - Use excerpt field provided by server

README.md, components/Header/Header.js, components/Meta.js, lib/gtag.js, next.config.js, pages/_app.js
* Implements Next.js Google Analytics solution: https://github.com/zeit/next.js/tree/canary/examples/with-google-analytics
=> CDP-1719 - Add support for Google Analytics

lib/elastic/api.js
- added documents and packages filter to typesPrioritiesRequest query
=> CDP-1795 - filter documents/packages from priorities query

config.js, pages/documentation/uploading-press-guidance.js, pages/documentation/uploadingvideo.js
- Adds static file url to config
- Adds uploading-press-guidance.js for creating press guidance documentation page
- Updates the title on the uploading video press guidance
=> CDP-1803: Adds Uploading Press Guidance Documentation Page

components/Footer/Footer.js, components/Results/NoResults.js, components/menus/UserProfile/UserProfile.js, components/navs/global/LoggedInNav/LoggedInNav.js, components/navs/global/LoggedOutNav/LoggedOutNav.js, config.js
Updated the broken feedback link in the user profile dropdown.
Since the feedback link appears in multiple places through the site, I added it as a variable in the config file and load the variable in everywhere rather than hardcoding it in multiple places.
=> [Hot Fix] CDP-1825: Correct feedback form link 

components/admin/FormikAutoSave/FormikAutoSave.js, components/admin/PackageEdit/PackageEdit.js
Deleting countries/bureaus from the package details page will now save
=> CDP-1804: Deleting countries/bureaus don't save

components/Featured/Packages/Packages.scss, components/Package/PackageCard/PackageCard.scss, components/popups/Popover/Popover.scss
- also, fix Packages responsive layout on homepage
- ADD TO CODE REVIEW IN SPRINT 51
=> CDP-1828 - Package file list display - handle long filenames

components/Video/Video.js
1723: Updates video copy by changing "Video with captions" to "Video with subtitles" and updates the download text to include "and social media."
2068: Updates the Video component so it force displays videos with subtitles if they exist. `getCaptions()` was only looking at `unit.source[0]` which is why sometimes the videos were displaying the subtitles over clean if both existed depending on which was `unit.source[0]`. I believe my update looks through `unit.source` to check if any of them have subtitles, and if not to return `false` to update the state.
Also, need to figure out what is up with my linting changes? It passed when I committed, but seems like a lot of space change differences.
=> 2068 and 1723 HOTFIXES

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js, components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.js, components/ScrollableTableWithMenu/TableHeader/TableHeader.js, components/ScrollableTableWithMenu/TableHeader/TableHeader.test.js
Provides fallback values for the state stored in the dashboard context. This prevents reference errors in cases where the dashboard renders before context loads.
=> CDP-2065: Fix dashboard errors

components/Register/UserDetails/validationSchema.js, config.js
* Update config & whitelistError msg for new support email address
* see also [https://github.com/IIP-Design/iip-static-assets/commit/eab59de0324a06def888f3f3b27a66d7d9e0c5e0](https://github.com/IIP-Design/iip-static-assets/commit/eab59de0324a06def888f3f3b27a66d7d9e0c5e0)
=> CDP-2126: Replace design@america.gov with gpadigitalhelp@state.gov

components/admin/ProjectEdit/GraphicEdit/AddGraphicFiles/AddGraphicFiles.js, components/admin/ProjectEdit/GraphicEdit/GraphicFilesFormContainer/GraphicFilesForm/GraphicFilesForm.js, components/admin/ProjectEdit/GraphicEdit/GraphicFilesFormContainer/GraphicFilesForm/__snapshots__/GraphicFilesForm.test.js.snap, components/admin/dropdowns/GraphicStyleDropdown/GraphicStyleDropdown.js, components/admin/dropdowns/GraphicStyleDropdown/GraphicStyleDropdown.test.js, package-lock.json
Remove Clean option when uploading Graphic
- Filters out clean option while mapping over dropdown options.
=> [CDP-2096] Removes Clean Option from Graphic upload

components/SearchInput/SearchInput.test.js, components/SearchInput/mocks.js
SearchInput fix was already in place, just needed a test
- Simple smoke test based on Edwin's other tests
- Basic mocks file
=> [CDP-2102] Adds Basic Test and Mocks for SearchInput

CHANGELOG.md, components/GraphicProject/GraphicProject.js, components/GraphicProject/utils.js, lib/sourceLogoUtils.js
* Displays the ShareAmerica logo in the graphic project preview if the project's owner is ShareAmerica
* Fixes display of project title on the preview modal from the graphic details page
=> CDP-2128: ShareAmerica logo should show if Source=ShareAmerica

components/FilterMenu/FilterSelections.js, components/Results/Results.js, components/Results/ResultsHeader/ResultsHeader.js, components/SearchInput/SearchInput.js, lib/elastic/query.js, lib/hooks/useAPIRequest.js
- results sorted by creation date
- sort by dropdown not relevant on this page so it is not displayed
- searches performed on this page will search on document type
=> CDP-2100 - Sort 'Browse All' guidance packages result page by creation date

components/admin/Upload/Upload.js, components/admin/Upload/modals/VideoUpload/VideoProjectFiles/VideoProjectFileDesktop/VideoProjectFilesRowDesktop.js, components/admin/Upload/modals/VideoUpload/VideoProjectFiles/VideoProjectFiles.js, components/admin/Upload/modals/VideoUpload/VideoProjectFiles/VideoProjectFilesMobile/VideoProjectFilesRowMobile.js, components/admin/Upload/modals/VideoUpload/VideoUpload.js, components/admin/dropdowns/LanguageDropdown/LanguageDropdown.js
- Principal change is providing the file name to the language dropdown.
- Also look for `-port` or `_port` rather than `port` for Portuguese.
Held off on a bigger refactor due to lack of time.
=> CDP-2142: Auto populate language dropdown on video upload

components/admin/EditFileGridRow/EditFileGridRow.js, components/admin/ProjectEdit/GraphicEdit/GraphicEdit.js, components/admin/Upload/modals/GraphicUpload/GraphicUpload.js, components/admin/Upload/modals/GraphicUpload/GraphicUpload.test.js, components/admin/Upload/modals/GraphicUpload/__snapshots__/GraphicUpload.test.js.snap, components/admin/dropdowns/GraphicStyleDropdown/GraphicStyleDropdown.js, lib/graphql/normalizers/graphic.js, lib/hooks/useFileStateManager.js
- allow files with "Clean" or "Shell" in filename to be uploaded with selected style selection
- display files in appropriate section on GraphicEdit page (Editable, Support, Graphic)
=> CDP 2160 - validate Graphic Upload by style selection instead of filename

components/Header/Header.scss
* Partially included with https://github.com/IIP-Design/content-commons-client/pull/252
* Adds `z-index` value to the header
=> CDP-2215: Add z-index to header

lib/elastic/api.js, pages/video.js
* Passes the `user` object to the `VideoPage` `getItemRequest` function.
=> CDP-2232: Fix 500 error on video project page

CHANGELOG.md, lib/elastic/api.js, package-lock.json, package.json
Reverts IIP-Design/content-commons-client#257
CDP-2233 was hot fixed to the master branch (PR #258).
=> Revert "CDP-2233 Video Display Issue"

lib/elastic/parser.js
* Adjusts the video languageUnit assignment to match the language parameter
=> CDP-2235: Video projects are displayed on the Home page based on first alphabet of the language associated with video

components/Document/DocumentCard/DocumentCard.scss, components/Featured/Priorities/Priorities.scss, components/Featured/Recents/Recents.scss, components/GraphicProject/GraphicCard/GraphicCard.scss, components/GraphicProject/GraphicProject.scss, components/admin/PackageEdit/PackageFiles/PressPackageFile/PressPackageFile.scss, components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.scss, components/admin/ProjectReview/VideoProjectFiles/VideoProjectFiles.scss, components/admin/ProjectUnits/ProjectUnitItem/ProjectUnitItem.scss, components/modals/ModalDescription/ModalDescription.scss, components/modals/ModalItem/ModalItem.scss, components/popups/Popover/Popover.scss, styles/mixins.scss
* Adjusts styling for text wrapping for home page priorities and various components app-wide
* Create mixin for hyphenation
=> CDP-2234: Adjust styling for text wrapping

CHANGELOG.md, README.md
Adds CSS modules documentation to the README file
=> CDP-2229: CSS modules documentation

CHANGELOG.md, components/Header/Header.js, components/Header/Header.test.js
This PR adds values for the `height` and `width` attributes for the DoS seal SVG, replaces the Semantic UI Header and Image components, and adds tests for the `Header` component.
=> CDP-2262: Add width and height to DoS seal SVG

CHANGELOG.md, components/admin/dropdowns/PolicyPriorityDropdown/PolicyPriorityDropdown.js, components/admin/dropdowns/PolicyPriorityDropdown/PolicyPriorityDropdown.test.js, components/admin/dropdowns/PolicyPriorityDropdown/mocks.js
This PR adds a `PolicyPriorityDropdown` component and unit test.
=> CDP-2334: Create a Priority Policy dropdown

lib/graphql/queries/playbook.js
Returns the content object from `PLAYBOOK_DETAILS_FRAGMENT`
=> CDP-2346: return content object from PLAYBOOK_DETAILS_FRAGMENT

components/admin/Dashboard/utils.js, lib/graphql/queries/playbook.js, lib/graphql/util.js, lib/utils.js
Add playbook content and count queries to the admin dashboard so that it doesn't crash when a team has only access to playbooks.
=> CDP-2404: Playbooks in dashboard

components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.js, components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.module.scss
Adds a second list below the file list with a placeholder animation for each file getting uploaded. As each file upload completes the placeholder is removed from the DOM.
=> CDP-2384: add loading animation when adding files to the resources section

pages/package/playbook/[id].js
Mirrors the change made to the playbook preview component.
=> Add client-side query to playbook frontend page

components/User/UserAdmin.js, components/admin/dropdowns/CopyrightDropdown/CopyrightDropdown.js, components/admin/dropdowns/CopyrightDropdown/CopyrightDropdown.test.js, components/admin/dropdowns/QualityDropdown/QualityDropdown.js, components/admin/dropdowns/QualityDropdown/QualityDropdown.test.js, components/admin/dropdowns/VideoBurnedInStatusDropdown/VideoBurnedInStatusDropdown.js, components/admin/dropdowns/VideoBurnedInStatusDropdown/VideoBurnedInStatusDropdown.test.js, components/admin/dropdowns/VisibilityDropdown/VisibilityDropdown.js, components/admin/dropdowns/VisibilityDropdown/VisibilityDropdown.test.js
Depends on the corresponding [server-side PR](https://github.com/IIP-Design/content-commons-server/pull/63). 
Also updates corresponding tests.
=> Replace queries dependent on client-side introspection

components/admin/PackageCreate/PackageCreate.js, components/admin/dropdowns/PackageTypeDropdown/PackageTypeDropdown.js
Updated `PACKAGE_TYPE_QUERY` to use a mutation and not an introspection query.
=> CDP-2461 Updated PACKAGE_TYPE_QUERY to use mutation and not introspection

components/admin/dropdowns/PolicyPriorityDropdown/PolicyPriorityDropdown.js, components/admin/dropdowns/PolicyPriorityDropdown/PolicyPriorityDropdown.test.js, lib/graphql/builders/playbook.js
This PR adds an empty option to `PolicyPriorityDropdown`.
=> CDP-2470: There is no "none" option on the policy priority dropdown.

components/Featured/Playbooks/Playbooks.js, components/Playbook/Playbook.js, components/Playbook/Playbook.module.scss
This PR adjusts the playbook header spacing and updates the playbooks archive date (CDP-2434).
=> CDP-2451: Adjust playbook header spacing
