components/Meta.js
lib/socialHeaders.js
pages/video.js

Port of CDP-1130 from version 1:
- Dynamically populates the header of server-side-rendered video pages with og and twitter meta tags (used for social sharing)
- Adds `og:site_name` meta header of "Content Commons" to all pages
- Makes section flagged in v1 as a bit hard to read more explicit

CDP-1177: Add social sharing headers to video pages

---

components/admin/Upload/modals/VideoUpload/VideoProjectFiles/VideoProjectFileDesktop/VideoProjectFileDesktop.js
components/admin/Upload/modals/VideoUpload/VideoProjectFiles/VideoProjectFilesMobile/VideoProjectFilesMobile.js
components/admin/Upload/modals/VideoUpload/VideoUpload.js

**CDP-1282: File of the same name and path can be uploaded in a project** 
Added a reduce function on the resulting setFiles to prevent duplicates when new files are added.
**CDP-1286: Files selected for upload should display in alphabetical order**
Added sorter to the file list that applies whenever a file is added or replaced.

Merge of CDP-1282 and CDP-1286

---

components/admin/Dashboard/MyProjects/MyProjectPrimaryCol/MyProjectPrimaryCol.js
components/admin/Dashboard/TeamProjects/TeamProjectPrimaryCol/TeamProjectPrimaryCol.js
components/admin/projects/ProjectEdit/PreviewProjectContent/PreviewProjectContent.js
components/admin/projects/ProjectEdit/PreviewProjectContent/PreviewProjectContent.scss
components/admin/projects/ProjectEdit/PreviewProjectContent/PreviewProjectContent.test.js
components/admin/projects/ProjectEdit/PreviewProjectContent/__snapshots__/PreviewProjectContent.test.js.snap
components/admin/projects/ProjectEdit/PreviewProjectContent/mocks.js
package-lock.json
package.json

* If there's only one language unit, display the language instead of a dropdown
* Display the tags at the bottom of the preview project modal
* Display the next available unit in the modal if the English unit has no files
* Adjust the key for the dashboard primary columns to address error in console
* update and add new tests where needed

CDP-1392-1393

---

components/admin/dropdowns/TagDropdown.js
components/admin/dropdowns/TagTypeahead.js
components/admin/dropdowns/dropdown.scss
components/admin/projects/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js
components/admin/projects/ProjectEdit/EditVideoModal/ModalForms/UnitDataForm/UnitDataForm.js
components/admin/projects/ProjectEdit/ProjectDataForm/ProjectDataForm.js

Additionally, renames the 'TagTypeahead' component 'TagDropdown' so as to be consistent with other dropdowns.

CDP-1414: Add RTL support for tag dropdown

---

components/admin/dropdowns/ProjectVisibilityDropdown/ProjectVisibilityDropdown.js

Renaming ProjectVisibility to Visibility in the GraphQL query

CDP-1525: Public/Internal File Visibility

---

components/ScrollableTableWithMenu/TableBody/TableBody.js
components/ScrollableTableWithMenu/TableBody/TableBody.test.js
components/ScrollableTableWithMenu/TableBody/mocks.js

Restructured TableBody so that the graphql HOC and TableBody component
can be exported independently allowing HOC props to be tested
Added test to check that subscribeToStatuses is called
Added tests for the updateProjectStatus function which runs when
subscription data is received

CDP-1520: Update TableBody Tests for Status Subscription

---

pages/_error.js
pages/admin/package/index.js
pages/admin/package/index.test.js

* Redirects to dashboard if !query.id
* Addresses Next.js trailing slash bug
* Adds test for `/package/index.js `
* Note: Redirect occurs on `/package/index.js` since the `[id].js` page is not loaded if there is no query.id. Without query.id, Next loads the `/package` route and `/package/` is redirected to `/package` instead of receiving a 404 (i.e., the Next trailing slash bug)

CDP-1614 - Redirect to dashboard if id is not present

---

next.config.js
package-lock.json
package.json

1. Adds an `npm run analyze` script which opens up a bundle analyzer window
2. Adds support for the optional chaining syntax (ex: `data?.name?.firstName` vs `data && data.name && data.name.firstName`)
3. Ran `npm audit fix` to correct sub-dependency vulnerability.

Bundle analyzer

---

CHANGELOG.md
components/admin/dropdowns/VisibilityDropdown/VisibilityDropdown.js

Only allows users to mark video projects as for public use, since the internal only option is not yet ready.
Rather than iterating over the results from the visibility query, I hardcode in one option, namely:
```js
{
key: 'PUBLIC',
text: 'Public (displayed on Content Commons)',
value: 'PUBLIC'
}
```
I've left the query in place and simply commented out the mapping over it's results to facilitate reintroducing this feature when we are ready.

HOT FIX - Constrain visibility options to public only

---

.eslintrc
components/admin/FormikAutoSave/FormikAutoSave.js
components/admin/PackageEdit/PackageDetailsFormContainer/PackageDetailsForm/PackageDetailsForm.js
components/admin/PackageEdit/PackageDetailsFormContainer/PackageDetailsFormContainer.js
components/admin/PackageEdit/PackageEdit.js

**CDP-1746 -** Disables re-initalization in the Formik component in `PackageDetailsFormContainer.js` to prevent unnecessary re-renders. @edwinmah - This takes care of the ticket you were assigned earlier today.
**CDP-1639 & CDP-1747 -** Use `pkg.id` to determine whether the form is new or existing, and therefore apply the correct validation schema  in the Formik component in the `PackageDetailsFormContainer.js`. Previously was using the non-existent `props.id` and therefore always loading the validation schema for a new form.
**CDP-1734 -** Replace an old Formik form validation method in the FormikAutoSave component so that autosave only fires when the form is valid. Also disable the `Save & Exit` action button when the form does not pass validation. If this were not disabled, clicking …

Package Details Page Validation Issues

---

components/admin/PackageEdit/PackageDetailsFormContainer/PackageDetailsFormContainer.js
components/admin/ProjectDetailsForm/ProjectDetailsForm.js

**CDP-1746 -** Previous fix removing `enableReinitialization` prop prevented data from newly uploaded documents from appearing. This modification tests for newly added documents, and if present conditionally enables reinitialization.
**Additional Changes -** Removes unused imported module in `ProjectDetailsForm.js`.

Reinitialization

---

CHANGELOG.md
pages/index.js

Adds a Department priorities box to the homepage using the search term `coronavirus covid`. Bumps all remaining boxes down one.

HOT FIX - Add coronavirus priorities section to the homepage

---

components/ContentHeightClamp/ContentHeightClamp.js
components/ContentHeightClamp/ContentHeightClamp.scss
components/ContentHeightClamp/ContentHeightClamp.test.js
components/Document/DocumentCard/DocumentCard.js
components/Document/DocumentCard/DocumentCard.scss
components/Document/DocumentCard/DocumentCard.test.js

* Excerpts longer than 144px in height are now cropped.
* Subtle fade appears at the bottom of cropped excerpts to indicate additional content can be viewed by scrolling
* Cropped excerpts are focusable and can be scrolled using keyboard by clicking `space` or `up` /`down` arrows
* Add tests for ContentHeightClamp and DocumentCard components

CDP-1785: Crop long excerpts displayed on DocumentCards

---

components/admin/ButtonPublish/ButtonPublish.js
components/admin/ButtonPublish/ButtonPublish.test.js
components/admin/PackageEdit/PackageEdit.js
components/admin/PackageEdit/PackageEdit.test.js
components/admin/PackageEdit/PackageFiles/PackageFiles.js
components/admin/PackageEdit/PackageFiles/PackageFiles.test.js

* Publish and Publish Changes buttons are disabled if a package has no files
* Added a message that at least one file must be uploaded before publishing to Content Commons
* Updated tests for PackageEdit, PackageFiles, and ButtonPublish

CDP-1790: Disable Publish button if no package files

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.js
components/ScrollableTableWithMenu/TableBody/TableBody.js
components/ScrollableTableWithMenu/TableHeader/TableHeader.js
lib/graphql/queries/package.js
lib/graphql/queries/video.js
package-lock.json
package.json

Passes the first, skip, and orderBy values to the queries `VideoProjectsByTeam` and `TeamPackagesQuery`. This allows for sorting and pagination to occur on the server rather than on the client after all results are returned.
However, special accommodations must be made to handle sorting of the author column because it is not possible to order by a nested property (i.e. the author returns a User type rather than a scalar name). As such, when sorting by author pagination props are not sent to the server, resulting in an overfetch which is then sorted on the client (line 127-152 of `TableBody.js`).
In order to take effect, these changes require analogous edits to the resolvers in the content-commons-server, which can be found a pull request with the same name in that repo.
Did not fix broken …

CDP 1814 - Dashboard Pagination

---

components/Featured/Packages/Packages.js
components/Featured/Packages/Packages.scss
components/Footer/Footer.js
components/Footer/Footer.scss
components/Footer/Footer.test.js
config.js

1. Adds a link to the press guidance archive to the bottom of the featured packages box
1. Conditionally adds a similar link to the footer, only displaying the link if the user is logged in
1. Adds tests for footer component 🎉
1. Replaces h1 elements in the footer with divs in the interest of improved accessibility
I did not write tests for the `Packages` component because they would require on `redux-mock-store` as a dependency. This dependency has been added on the develop branch but hasn't made it to the master branch yet. For this reason, and because it is a pretty trivial change, I plan to write the accompanying `Packages` tests when I merge the hotfix back into develop.

[HOT FIX] CDP 1833 - Add link to press guidance archive

---

lib/redux/actions/postType.js

- Removes Guidance Packages as an option in Format filter options
- Renames Document type in filter list

CDP-2022 & CDP-2023

---

components/Meta.js
pages/_app.js
pages/_document.js

- Adds production GTM snippet to the Head via the Meta file. This replaces the current implementation.
- Adds `<noscript>` snippet to the body via the main `_app.js` by using `componentDidMount()` and appending the snippet to the body. I know this is likely not the appropriate way to achieve that, but it's what I got to work so am looking forward to seeing notes.
* And just for clarification on the `<noscript>` snippet. This is just a fallback for the analytics incase the script is not running on the page for some reason.
Additionally, this implementation will be duplicated across Development and Staging. HOWEVER, it is a different snippet, so the code should not be rolled back.

CDP-2021 (HOTFIX)

---

components/FilterMenu/FilterMenuItem.js
components/FilterMenu/FilterSelections.js
components/SearchInput/SearchInput.js
lib/redux/actions/postType.js

- Cherry-picks the commit implementing CDP-2022 & CDP-2023 (remove filter by package, add filter by document, respectively) from develop.
- Removes `package` from the list of selected filter items (CDP-2074).
- Remove the package content type from the query when another content type is selected. (CDP-2075)
- When running a search from the packages browse all page, it resets the post type filter from package to document (CDP-2075)
Note - It is still possible to see packages in search results if you search with no content filters at all. We can resolve this changing the query default from no specified content type to all content types but `package`.

Hot Fixes - CDP-2022, CDP-2023, CDP-2074, CDP-2075

---

components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js

Pulls the content type off of the context object rather than depending on a hardcoded ternary. Having issues with getting the Apollo mock provider working in conjunction with mocked context, so in the interest of time am pushing without updated tests.

CDP-1968: Hook up the unpublish functionality in the dashboard for graphics

---

CHANGELOG.md
components/Footer/Footer.js
components/Footer/Footer.test.js

Changes the footer questions and feedback link to "gpadigitalhelp@state.gov" from "design@america.gov"

CDP-2114: Change footer feedback link to gpadigitalhelp@state.gov

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js
components/ScrollableTableWithMenu/TableRow/TableRow.js

- remove premature stopPolling fn call in useEffect in UnpublishProject
- display updating text on gql publishing success instead of default text in TableRow for project status
- cleanup syntax

CDP-2110 - Fix for UNPUBLISH/PUBLISH SUCCESS Text Display when updating Graphic Projects

---

CHANGELOG.md
components/Share/Share.js
components/Share/Share.test.js

* Removes social share buttons from the share dropdown in the graphic preview modal and commons page
* Updates tests for Share component

CDP-2125: Remove share buttons for graphics

---

lib/elastic/query.js

- account for public user.id in search query

Fix for press docs displaying in search results for logged out users

---

CHANGELOG.md
components/admin/ProjectEdit/GraphicEdit/GraphicSupportFiles/GraphicSupportFiles.js
components/admin/ProjectEdit/GraphicEdit/GraphicSupportFiles/GraphicSupportFiles.test.js

* Uses `updateGraphicProject` mutation to handle deletion of graphic support files. Previously, `deleteSupportFile` was used. I had to do a refetch of the `GRAPHIC_PROJECT_QUERY` to get the UI to update. Maybe there's a better way because I didn't think a refetch would be necessary if `updateGraphicProject` is used.
* Updates test data for GraphicSupportFiles to use updateGraphicProject

CDP-2028: Deleting a file from a Publish Project did not display Publish Changes button

---

CHANGELOG.md
components/admin/ButtonPublish/ButtonPublish.js
components/admin/ButtonPublish/ButtonPublish.test.js
components/admin/ProjectEdit/GraphicEdit/GraphicEdit.js
components/admin/ProjectEdit/GraphicEdit/GraphicFilesFormContainer/GraphicFilesForm/GraphicFilesForm.js
components/admin/ProjectEdit/GraphicEdit/GraphicFilesFormContainer/GraphicFilesForm/GraphicFilesForm.test.js
components/admin/ProjectEdit/GraphicEdit/GraphicFilesFormContainer/GraphicFilesForm/mocks.js
components/admin/ProjectEdit/GraphicEdit/__snapshots__/GraphicEdit.test.js.snap

* Includes CDP-1932
* Disables the unpublish button on the graphic project details page if there are no graphic files. Previously, the unpublish button was always enabled
* Sets the `disableBtns` state based on the presence of graphic files. Previously, `disableBtns` was set to `true` if there were no graphic files and never reset to `false`
* Adjusts the no files message to instruct the user to upload at least one graphic file, if it's an existing project.
* Returns the graphic project `type` when the `updateGraphicProject` mutation is called to delete a graphic file. This allows the `useIsDirty` hook to return `true` when a graphic file is deleted, which displays the Publish Changes button. This change addresses CDP-1932.

CDP-2130: Save & Exit/Preview/Publish buttons should become active once 1+ graphic files added to project from edit page

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js
context/dashboardContext.js
lib/graphql/queries/graphic.js

- need to keep UnpublishProjects mounted (as opposed to only mounting if a published project is selected) so polling is not stopped before the status of projects is updated
- using a new query in UnpublishProjects to only fetch the id, status & publishedAt fields for graphic content instead of querying all graphic content (imgs) which were creating a network strain when polling (all the imgs were continuously being downloaded)
- removed calling stopPolling as that was preventing status updates from completing

CDP-2110 - Dashboard status change not updating correctly

---

CHANGELOG.md
components/GraphicProject/GraphicCard/GraphicCard.js
components/GraphicProject/GraphicCard/GraphicCard.test.js
components/GraphicProject/GraphicProject.js
components/GraphicProject/GraphicProject.test.js
components/GraphicProject/utils.js
lib/elastic/parser.js

* Displays "Internal Use Only" message in graphic project previews and result cards if a project has been marked INTERNAL
* Updates tests for GraphicProject and GraphicCard

CDP-2134: Add Internal Use Only flag to graphic projects on Commons when they are marked as Internal on Publisher

---

components/Post/Post.js
components/Post/Post.test.js
lib/hooks/useSignedUrl.js

- Pass plain URL (rather than a signed URL) to the post modal image
- Update corresponding tests
- In `useSignedUrl` hook, check for presence of AWS access key in URL before attempting to convert to a signed URL.

CDP-2135: Double signing of post featured image urls

---

CHANGELOG.md
components/GraphicProject/GraphicProject.js

* Uses the support files editable field as the condition to collate graphic project support files. Previously, the condition was based on based on the presence of a file's extension in an array of editable extensions.

CDP-2139: When users are not logged in and they preview a Project Modal, the 'Other' tab displays weird download characters.

---

components/navs/global/LoggedOutNav/LoggedOutNav.js
components/navs/global/LoggedOutNav/LoggedOutNav.test.js
components/navs/global/global.scss

Subscribers should be able to land on the homepage and see a pop up near the login button to remind them, they have to login in order to see internal content like Press Guidances and Editable Graphics files.
- Adds a new stateful variable to track the visibility
- Uses CSS positioning to match mocks
- Sets timeout in useEffect to delay showing
- Sets timeout in useEffect to delay removal
- Allows manual removal as well

[CDP-2066] Adds login reminder after 5 seconds, timeout and manual close

---

CHANGELOG.md
components/Package/Package.js

* Displays press guidance package documents in the order of releases, guidances, and transcripts
* Groupings per press team:
**Releases**
* Fact Sheet
* Media Note
* Notice to the Press
* Readout
* Taken Questions
* Statement
* Travel Alert
* Travel Warning
**Guidances**
* Press Guidance
**Transcripts**
* Background Briefing
* Department Press Briefing
* Interview
* On-the-record Briefing
* Remarks
* Speeches

CDP-2055: Open a PG package and see in order, 1. releases, 2. guidances, and 3. transcripts

---

CHANGELOG.md
components/admin/ProjectEdit/GraphicEdit/GraphicEdit.js
components/admin/ProjectEdit/GraphicEdit/__snapshots__/GraphicEdit.test.js.snap

* Disables the delete button on the details page for published graphic projects
* Updates `GraphicEdit` test snapshot

CDP-2163: Delete button should be disabled for published graphic projects

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js
components/admin/Dashboard/TeamProjects/TeamProjects.js
components/admin/Dashboard/utils.js
context/dashboardContext.js
lib/graphql/queries/package.js
lib/graphql/queries/video.js

- updated UnpublishProjects to use new metaContent query for all types 
- this ensures ScrollableTableWithMenu is re-rendered
- lowers network strain by reducing data requested
- refactored ScrollableTableWithMenu so NOOP query no longer needed
- initialState not needed in dashboardContext
- set initial state for dashboardReducer in TeamProjects, setting team and queries which is passed 
onto DashboardContext provider

CDP-2159 - Unpublishing from Dashboard not working

---

.github/workflows/pull-request.yml
components/Video/Download/__tests__/DownloadCaption.test.js
lib/utils.js

- Ensure that a URL is always passed and a key only sent when relevant
Incidentally takes an opportunity to add dependency caching for GitHub actions, which should speed up the automated on pull requests test runner.

Vid downloads

---

components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js
components/admin/ProjectEdit/EditVideoModal/ModalSections/FileSidebar/FileSidebar.js

* Updates labeling for videos in `FileSidebar` to reflect changes in `VideoBurnedInStatusDropdown` text
* Switched the presentation order of `UseDropdown` and `VideoBurnedInStatusDropdown` to match mocks

CDP-2167: Videos are incorrectly labeled on "Videos in Project" screen

---

CHANGELOG.md
components/GraphicProject/GraphicProject.js
components/GraphicProject/GraphicProject.test.js
components/GraphicProject/graphicElasticMock.js
components/GraphicProject/graphicGraphqlMock.js
components/Results/ResultItem/ResultItem.js
components/admin/Previews/GraphicPreview/mocks.js
components/admin/ProjectDetailsForm/GraphicProjectDetailsFormContainer/GraphicProjectDetailsFormContainer.js
components/admin/ProjectDetailsForm/GraphicProjectDetailsFormContainer/GraphicProjectDetailsFormContainer.test.js
components/admin/ProjectDetailsForm/GraphicProjectDetailsFormContainer/mocks.js
components/admin/ProjectDetailsForm/ProjectDetailsForm.test.js
components/admin/ProjectDetailsForm/__snapshots__/ProjectDetailsForm.test.js.snap
components/admin/Upload/Upload.test.js
components/admin/dropdowns/TeamDropdown/TeamDropdown.test.js
components/admin/dropdowns/TeamDropdown/mocks.js
context/mocks.js
lib/sourceLogoUtils.js

- Changes team name to GPA Design & Editorial
- Updates applicable tests
To complete task, the following scripts need to be run:
**On the server:**
```mutation UPDATE_TEAM {
updateTeam(data: {
name: "GPA Design & Editorial"
}, where: {
id: "[ID]"
}) {
id
name
}
}
```
**On the API via Kibana:**
```POST graphics/_update_by_query
{
"script": {
"source": "ctx._source.owner='GPA Design & Editorial'",
"lang": "painless"
},
"query": {
"match": {
"owner.keyword": "GPA Editorial & Design"
}
}
}
```

Change team name to 'GPA Design & Editorial'

---

components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.test.js
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/mocks.js

* Sets the Language & On-Screen Text dropdown values for Clean videos in edit modal

CDP-2155: Adjust Language & On-Screen Text values on initial edit video modal load

---

CHANGELOG.md
components/GraphicProject/GraphicProject.js
components/admin/ProjectDetailsForm/GraphicProjectDetailsFormContainer/GraphicProjectDetailsFormContainer.js
components/admin/ProjectDetailsForm/GraphicProjectDetailsFormContainer/GraphicProjectDetailsFormContainer.test.js
lib/graphql/queries/graphic.js
lib/sourceLogoUtils.js

* Includes CDP-2201: As a publisher on the Design & Editorial team, I want to be able to select Regional Media Hubs as a Source
* Adds "Regional Media Hubs" to the graphic details form source dropdown and to the dashboard graphic queries
* Displays the DoS logo and "Regional Media Hubs" as the source in the graphics card and preview modal

CDP-2205: Display DOS seal for regional media hubs logo

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
lib/graphql/queries/graphic.js
lib/graphql/queries/package.js
lib/graphql/queries/video.js

Made the `team` parameter in the Dashboard Team queries a `TeamWhereInput` type to configure what content from different teams a specific team can see.  For example, the GPA Design & Editorial team can see its own content plus that of ShareAmerica and Regional Hubs while the U.S. Missions team can see only the content it creates.
Updated the Graphic, Video and Package queries.

CDP-2213 - Make team a where clause

---

CHANGELOG.md
components/Video/Video.js
components/Video/Video.test.js

* Removes the Transcripts tab from the video download popup on Commons

CDP-2146: Remove Transcripts tab from video download popup

---

CHANGELOG.md
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataFormQueries.js
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/mocks.js
components/admin/ProjectReview/VideoReview/VideoReview.js
components/admin/ProjectUnits/ProjectUnits.js

* Fixes a bug where deleting a video file from a published video's details page would not display the Publish Changes button. Fixed by calling the `updateVideoProject` mutation and passing the `projectTile` as the updated data when a video file is removed.
* Fixes a bug where changing a video file's language would not display the Publish Changes button. Fixed by calling the `updateVideoProject` mutation and passing the `projectTile` as the updated data when a video file's language is changed.
* Fixes a bug where changing a video file's type would not display the Publish Changes button. Fixed by calling the `updateVideoProject` mutation and passing the `projectTile` as the updated data when a video file's dropdown value is changed.
* Disables the Publish Changes button on the video review …

Video publish changes fixes

---

CHANGELOG.md
components/Page.js
components/PageTypes/ContentPage/ContentPage.js
components/admin/ProjectEdit/GraphicEdit/GraphicEdit.js
components/admin/ProjectEdit/GraphicEdit/GraphicEdit.test.js
components/admin/ProjectEdit/VideoEdit/VideoEdit.js
components/download/DownloadItem/DownloadItemContent.scss
components/menus/menu.scss
pages/_document.js
styles/styles.scss

* Adjusts the default link colors to meet the 4.5:1 contrast requirement and displays an underline on hover for links in the main content. The underline is necessary if we're going to display links (non-hovered) with color only (i.e., no underline). See https://www.w3.org/WAI/WCAG21/Techniques/general/G183.
* Adds `id="content"` to the `<main>` element.
* Adds smooth scrolling for users who have no preference for `prefers-reduced-motion`.
* Uses `padding` instead of `margin` for the content container since clicking the skip to content link results in the top of the page being hidden by the fixed navigation.
* Sets `position` to `relative` on the content container and adjusts the `top` value for the `GraphicEdit` and `VideoEdit` notification. This is to account for the use of `padding` …

CDP-2217: Add skip to content link

---

components/Featured/Recents/Recents.scss

* Adjusts styling for long titles in home page cards so that they break properly.

CDP-2234: Home page titles are not breaking correctly

---

CHANGELOG.md
lib/elastic/api.js
package-lock.json
package.json

Video is not displaying on the home screen when there are internal projects.  This is due to the query targeting any visibility and setting the size to 3.  If there are internal projects within the 3 returned results, the server will strip them (if the user is not logged in) leaving < 3 sent to the client.  The section will not display on the Home page if less than 3 results are returned. This is fixed by specifically targeting PUBLIC projects in the query.

CDP-2233 Video Display Issue

---

lib/elastic/api.js

* Adds the language query for the `post` content type in the recents Elasticsearch query. Previously, the language query was only added for the `video` content type.
**Note:** I didn't add the language query for graphics since we're selecting the Twitter graphic for display and since graphics didn't have the language query prior to PR #258

CDP-2236: Fix non-English language content from appearing by default on the home page

---

CHANGELOG.md
pages/graphic.js
pages/video.js

* Fixes the 500 error displayed for users who are not logged in when you share/copy the link on modal by checking for a logged in user before calling `getItemRequest` on the graphic and video pages.

CDP-2237: Fix the 500 error displayed for users who are not logged in when you share/copy the link on modal.

---

pages/graphic.js
pages/video.js

The user was being redirected to login screen for public content. Remove the check for the user on the client and let the server determine is content should be returned based on a valid user token being present.

fix: users were being directed to login page for public content

---

components/admin/ProjectEdit/VideoEdit/VideoEdit.js
components/admin/ProjectReview/VideoReview/VideoReview.js
pages/admin/project.js

Includes a little cleanup and refactoring, but the core of the fix is on line 73 of `pages/admin/project.js`. Namely, `loadReviewComponent();` should be `return loadReviewComponent();`.
Also, explicitly set the action to `review` on the review action button redirect.

fix: properly return the loadReviewComponent render function

---

components/Post/Post.js

Fix the dependencies array in the post component. The really problematic one was the second one since the if router was included as a dependency and also updated by the useEffect hook. So each time the hook ran it updated the router, thereby initiating another running of the hook.

fix: update dependency arrays in the posts component useEffect

---

CHANGELOG.md
components/Featured/Packages/Packages.js
components/Featured/Priorities/Priorities.js
components/Featured/Priorities/Priorities.scss
components/Featured/Recents/Recents.js
components/Featured/Recents/Recents.scss
components/Footer/Footer.js
components/Header/Header.js
components/Page.js
components/Results/ResultItem/ResultItem.js
components/Results/ResultItem/ResultItem.scss
components/admin/Dashboard/Dashboard.js
components/admin/Dashboard/TeamProjects/TeamProjectPrimaryCol/TeamProjectPrimaryCol.js
components/admin/ProjectUnits/ProjectUnitItem/ProjectUnitItem.js

This PR includes CDP-2243, CDP-2244, CDP-2248, and CDP-2249.
- Adds missing `alt` text values. Most of the violations were for the video cards on the search results page, but there were a few others as well. Ideally, `alt` text should describe the image, but there's not really a way to do that programmatically without some form of AI, but even AI can be suspect since it can reflect algorithm biases. So I set the missing values to the title, which eliminates the `src` url from being announced. The only other alternative is to treat the thumbnails as decorative and give the `alt` attribute empty string values.
- Adds an `aria-label` to the "Browse All" links on the home page. Because there are multiple "Browse All" links, screen reader users would find it confusing to see so many links with …

CDP-2243: Fixes missing alt text

---

components/SearchTerm/SearchTerm.js
components/SearchTerm/SearchTerm.module.scss
components/SearchTerm/SearchTerm.scss
components/SearchTerm/SearchTerm.test.js
components/SearchTerm/mocks.js

This PR adds a page title to the search results page and creates live regions for the search term and hits. The live regions allow screen readers to make an announcement whenever the search term or number of hits changes.
This PR also uses CSS modules for the `SearchTerm` component and replaces the Semantic UI Header component, which resulted in a 17 KB (gzipped) savings.

CDP-2327: Fix page title for search results page

---

components/FilterMenu/FilterMenu.js
components/FilterMenu/FilterSelections.js
lib/redux/reducers/filter.js
lib/redux/store.js
pages/_app.js
pages/results.js

Refactor the results page to use `getServerSideProps` rather than get `initialProps`.
As part of this update I added a `HYDRATE` action reducer to handle changes initiated by `next-redux-wrapper`. Also save dates as strings rather than objects so that they can be serialized when getting `getServerSideProps`.
Also addresses CDP-2316.

CDP-2314: Allow results pages to be refreshed/directly navigated to

---

components/ButtonAddFiles/ButtonAddFiles.js
components/admin/FileList/FileList.js
components/admin/FileList/FileList.module.scss
components/admin/PlaybookEdit/PlaybookEdit.js
components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.js
components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.module.scss
components/admin/ProjectEdit/GraphicEdit/GraphicSupportFiles/GraphicSupportFiles.js
components/admin/ProjectEdit/GraphicEdit/GraphicSupportFiles/GraphicSupportFiles.scss

Focused on getting the UI in place since the publish mutations aren't hooked up yet. As such, the add and remove file actions simulate the uploading/removing of files rather than kicking off actual mutations.
Since I used the graphics support file list as a starting point, I that out into a reusable `FileList` component that can be utilized in a couple other places reducing redundancy. The original had a number of nested CSS properties which I switched to CSS modules so we may want to double check at some other break points to make sure it looks good everywhere. Additionally, tests need to be extracted from the portion of the `GraphicSupportFiles.test.js` file that pertains to the file list.

CDP-2381: Add resources section

---

components/admin/PackageCreate/ButtonPackageCreate/ButtonPackageCreate.js
components/admin/PackageCreate/ButtonPackageCreate/ButtonPackageCreate.module.scss
components/admin/PackageCreate/PackageCreate.js
components/admin/PackageCreate/PackageCreate.module.scss
components/admin/PackageCreate/PackageForm/PackageForm.js
components/admin/PackageCreate/PackageForm/PackageForm.module.scss
components/admin/PackageCreate/PackageForm/PackageType/PackageType.js
components/admin/PackageCreate/PackageForm/TextInput/TextInput.js
components/admin/PackageCreate/PackageForm/TextInput/TextInput.module.scss
components/admin/PackageCreate/PackageForm/validationSchema.js
components/admin/PackageEdit/PackageFiles/PressPackageFile/PressPackageFile.module.scss
styles/mixins.scss

Adds a character count validation to Playbook internal description field.  Does this by adding validation to the TextInput component to make functionality available for other contexts. In addition, this PR addresses a few other issues:
- Updates schema and validates form when the Package types is changed
- Moves package create functions to the ButtonPackage create component
- Determines team package types in the PackageCreate screen and passes types thru props to make it less error prone and to avoid the whole PackageType/ContentType confusion
- Removes functionality specific for the "Press Guidance" team, e.g. title is pre-populated for the press team, and treats the Package type the same regardless of team.
- Updates various styles

CDP 2337 - Add character count validation to internal description field

---

CHANGELOG.md
components/admin/PlaybookEdit/PlaybookEdit.js
lib/graphql/queries/playbook.js

This PR replaces the mock mutation in `PlaybookEdit` with an actual `updatePlaybook` mutation. See also the server PR #59.

CDP-2400: Save Playbook text editor data

---

components/admin/PlaybookEdit/PlaybookEdit.scss

The `PlaybookEdit` action buttons were hidden under the site's fixed header. This was occurring because we're not using the Semantic UI container to wrap the page. I added `padding` to the page to reveal the page's header and action buttons and match the appearance of other edit pages.
The functionality of the Save & Edit button was already in place. That is, clicking on the button redirected to the dashboard as expected.

CDP-2395: Implement Save & Exit button

---

CHANGELOG.md
components/admin/PlaybookEdit/PlaybookEdit.js
components/admin/TextEditor/TextEditor.js

This PR addresses a bug where calling the `updatePlaybook` mutation in the `TextEditor` component resulted in the following GraphQL error:
```
Error: The relation DocumentConversionFormatToPlaybook has no node
for the model Playbook connected to a Node for the model DocumentConversionFormat
on your mutation path.
```
I replaced the `update` in the `data` tree with an `upsert`. In addition, I added a cache refresh to the mutation based on behavior observed on dev.

CDP-2403: GraphQL error when I tried to save using the Text Editor

---

components/admin/PlaybookEdit/PlaybookEdit.js
components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.js
components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.test.js
hocs/withApollo.js
lib/graphql/queries/playbook.js

Replaces the simulated file upload action in the `PlaybookResources` component with an actual upload function that saves the files to S3 and runs a GraphQL mutation to update the `supportFiles` field on the playbook.
- Adds the support files fragment to the playbook query in `lib/graphql/queries/playbook.js`
- Adds a custom merge function for playbook support files to optimize the cache behavior

CDP-2399: Connect the Additional Resources file uploader

---

components/admin/ActionButtons/ActionButtons.js
components/admin/ActionButtons/ActionButtons.test.js
components/admin/PlaybookEdit/PlaybookEdit.js
lib/graphql/queries/playbook.js

Corresponds to [PR #60 on the server](https://github.com/IIP-Design/content-commons-server/pull/60).
Adds the delete playbook query to the list of playbook queries.
Also updates the `ActionButtons` component so that it can display multiple content types rather than the binary `project` or `package`.

CDP-2393: Hook up delete resolver

---

components/admin/PackageCreate/PackageCreate.js
components/admin/PackageCreate/PackageForm/PackageForm.js
components/admin/PackageCreate/PackageForm/PackageForm.module.scss
components/admin/PackageCreate/PackageForm/TextInput/TextInput.js
components/admin/PackageEdit/PackageEdit.test.js
components/admin/PackageEdit/PackageFiles/PackageFiles.js
components/admin/PackageEdit/PackageFiles/PackageFiles.test.js
components/admin/PackageEdit/PackageFiles/mocks.js
components/admin/PlaybookEdit/PlaybookEdit.test.js

PR resets the form to its initial values when the package type is changed.  If the selected package type is 'Guidance', sets the name to the format: Guidance Package [date]
In addition, PR:
- Fixes skipped tests to work with new form
- Updates TextInput to conditional add props, add status role and enhance function docs 
- Makes checkbox error text red

CDP 2340 - Set form to initial values when package type is changed

---

components/ScrollableTableWithMenu/TableActionsMenu/TableActionsMenu.scss
components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.js
components/ScrollableTableWithMenu/TableActionsMenu/UnpublishProjects/UnpublishProjects.module.scss
components/admin/Dashboard/utils.js
lib/graphql/queries/playbook.js

Connects the unpublish and delete bulk actions on the dashboard to the relevant GraphQL mutations. There is a [corresponding PR on the server](https://github.com/IIP-Design/content-commons-server/pull/62) to delete files from S3 on unpublish/deletion, but it is not strictly speaking necessary for the bulk actions to work.
Also took care of a couple of targets of opportunity:
1. Changed the operation name `query Playbook($id: ID!)` to `query PLAYBOOK_QUERY($id: ID!)` per our dev meeting [discussions on consistency](https://iip-design.github.io/lab-tools/dev_meetings/2021-06-15.html#1-graphql-operation-names). 
2. Scoped the `UnpublishProjects` CSS to fix a couple of Sementic UI overrides.

CDP-2394: Hook up unpublish and delete from dashboard

---

CHANGELOG.md
components/Playbook/Playbook.js
components/Playbook/mocks.js
components/admin/Previews/PlaybookPreview/PlaybookPreview.js
components/admin/Previews/PlaybookPreview/PlaybookPreview.module.scss
components/admin/Previews/PlaybookPreview/PlaybookPreview.test.js
pages/admin/package/playbook/preview/[id].js

This PR is a follow up to PR #297 and #298.
* Creates a `PlaybookPreview` component that will render `Playbook` with server side data if available. If the data from the server is `undefined`, then data is fetched using a client query.
* Makes unavailable the share URL and support files downloading
* Preview opens in the same window for now, per UX.

CDP-2392: Implement preview from Playbook edit page

---

components/admin/ButtonPublish/ButtonPublish.js
components/admin/ButtonPublish/ButtonPublish.test.js
components/admin/TextEditor/TextEditor.js

This PR prevents the `updateMutation` from being called when the playbook text editor is loaded, and it also addresses the styling of the Publish Changes button at the bottom of the playbook details page.

CDP-2429: Publish Changes displays after a project is published

---

components/ScrollableTableWithMenu/TableActionsMenu/DeleteProjects/DeleteProjects.js

When deleting a playbook from the dashboard the confirmation message will now say 
`Are you sure you want to delete the selected DRAFT playbook?`
or in the case of multiple packages selected:
`Are you sure you want to delete the selected DRAFT playbooks?`.
Similarly, I removed the word "project" from the confirmation message for packages.

CDP-2406: Update delete confirmation from dashboard

---

components/admin/Dashboard/TeamProjects/DetailsPopup/DetailsPopup.js
components/admin/Dashboard/TeamProjects/DetailsPopup/PackageDetailsPopup.js
components/admin/Dashboard/TeamProjects/DetailsPopup/PlaybookDetailsPopup.js
components/admin/Dashboard/utils.js
lib/graphql/queries/playbook.js

Creates a `PLAYBOOK_FILES_QUERY` and the `PlaybookDetailsPopup` component to render the list of playbook support files in the dashboard.
Also, for completeness, sets the `PLAYBOOK_FILES_QUERY` as the files query for playbooks in the `admin/Dashboard/utils.js` function `setQueries`, although that value is never used.

CDP-2418: Populate the file list for playbooks in the dashboard

---

components/Playbook/Playbook.js
components/Playbook/Playbook.module.scss
components/ScrollableTableWithMenu/TableActionsMenu/DeleteProjects/DeleteProjects.js

This PR places a limit on the width of the title on the playbook and playbook preview page and two miscellaneous fixes.
1. Added an adjustment to the conditional check for  `item.supportFiles.length` to prevent a `0` from being rendered on the playbook page. This was causing the blue bar to appear at the bottom even when there are no support files.
2. Replaced "Content Cloud" with "Content Commons" in the delete confirmation modal.

CDP-2436: Limit width of playbook title

---

components/Playbook/Playbook.js
components/admin/download/DownloadPkgFiles/DownloadPkgFiles.js
components/admin/download/DownloadPkgFiles/SignedUrlLink/SignedUrlLink.js
components/admin/download/DownloadVideo/DownloadVideo.js
components/download/DownloadItem/DownloadItemContent.js

The `url` field on the playbook data object returns an asset path to the file without the bucket URL prefix. Using the `signedUrl` property on the playbook would work, however, that currently provides a link to the asset in the authoring bucket rather than the production bucket (not sure why that is the case).
However, my using the `maybeGetUrlToProdS3` function, we can convert that asset path to the actual S3 URL before trying to derive a signed URL to the asset.
Also made some trivial tweaks to whitespace and import statement order in a couple of other files.

CDP-2432: Correct file links to playbook additional resources

---

components/ScrollableTableWithMenu/ScrollableTableWithMenu.js
components/ScrollableTableWithMenu/TableMenu/TableMenu.js
lib/graphql/queries/playbook.js

This PR addresses a number of issues.
1. [CDP-2456](https://design.atlassian.net/browse/CDP-2456) - The playbooks appearing in wrong order on the dashboard. This was resolved by adding an `orderBy` variable to the team playbooks query in `lib/graphql/queries/playbook.js`. This allows for the query to be sorted in descending order (most recent created first).
2. This change also enabled sorting the table content by clicking on the column headers.
3. Similarly, added a search term variable to the team playbooks to allow for playbook search from the dashboard.
4. Added the locale value to category return on playbooks query (also in `lib/graphql/queries/playbook.js`) so that the categories column can get populated.
5. [CDP-2396](https://design.atlassian.net/browse/CDP-2396): altered the case …

Dashboard Fixes

---

components/Playbook/Playbook.js
components/admin/ProjectReview/VideoReview/VideoReview.js
components/admin/Upload/modals/Confirm/Confirm.js
lib/elastic/api.js
lib/elastic/parser.js
pages/_app.js
pages/package/playbook/[id].js

Removes `getServerSideProps` from the page entirely since the query depends on the current user object, which is only available on the client side.
Incidental updates:
- Fetch the current user in the `_app` component's `getInitialProps` and pass it as a prop to the child component.
- Use the filename rather than id for the additional resources list key since the support file id is not available on the ES query response.
- Replace instances of `Content Cloud` with `Content Commons`.

CDP-2462: Switch playbook query on playbook frontend from GraphQL to Elasticsearch 

---

components/Results/ResultsHeader/ResultsHeader.js
components/Results/ResultsHeader/ResultsHeader.module.scss
components/Results/ResultsHeader/ResultsHeader.test.js
lib/elastic/api.js
lib/redux/actions/postType.js

This PR addresses the following items/tickets:
- CDP 2449 - Alphabetizes the items in the format filter menu
- CDP 2446 - Hides the toggle list/gallery display on the results screen
- CDP 2448 - Removes the border on the sort by dropdown on the results screen so the '-' is hidden when Guidance Packages are viewed (this would happen when the Guidance Packages 'Browse All' link was clicked on the anding page)
- CDP 2459 - Removes the Playbook and Press Guidance checkboxes from the Format filter menu on the results screen when a user is not logged in

Addresses several bug tickets

---

components/admin/PlaybookEdit/PlaybookEdit.js
components/admin/TextEditor/TextEditor.js
components/admin/TextEditor/TextEditor.test.js

This PR fixes two `TextEditor` autosave bugs and adds handling for the green "Changes saved" message.
Previously, removing all content from the text editor would not trigger autosave. This was happening because `!editor.getData()` was a condition in the autosave early return. Removing that condition fixed this bug.
However, in the process of fixing this bug, I discovered that autosave would not be triggered if a user removes some content from the text editor and then adds back the *same* content in the same location. (I'd described this bug briefly during one of the stand ups.) This was happening because of a fix in PR #311, which added `editor.getData() === content?.html` as a condition in the autosave early return. When the text editor is instantiated, it holds on to the value of …

CDP-2442: Removing all content from the text editor does not trigger autosave

---

components/Playbook/Playbook.js
components/Playbook/Playbook.module.scss
components/Playbook/Playbook.test.js
components/Playbook/PlaybookCard/PlaybookCard.module.scss
components/Playbook/mocks.js

This PR includes the following changes:
* Addresses the extra white space at the bottom of playbook pages. The extra white space is coming from `560px` of `padding-bottom` on `main`. Since the `main` padding affects the entire site, my solution is temporary until that extra `padding` can be refactored off `main`. I suspect the extra `padding` is related to the sticky `footer`, which could also be handled in a more modern approach with `flexbox`. Regardless, I created a separate ticket, [CDP-2468](https://design.atlassian.net/browse/CDP-2468), for refactoring and handling this in a better way more time is available.
*  Increases the policy badge text size and weight on the playbook page to make it more readable. In addition, policy badges with a theme color that don't meet AA contrast …

CDP-2452: Remove extra white space at the bottom of playbook pages

---

components/admin/PlaybookEdit/PlaybookResources/PlaybookResources.js
components/admin/ProjectEdit/GraphicEdit/SupportFiles/SupportFiles.js

Adds the type property to the update playbook mutation when removing support files. This ensures that the playbook `updateAt` date is updated thereby toggling `isDirty`.
Also simplifies the `GraphicEdit/SupportFiles` component. There are no substantive changes to that component, just makes it a bit more compact.

CDP-2460: Enable publish changes button when a support file is removed

---

components/Playbook/Playbook.controller.js
components/Playbook/Playbook.js
components/Playbook/Playbook.test.js
components/Playbook/PlaybookCard/PlaybookCard.js
components/Playbook/PlaybookCard/PlaybookCard.module.scss
components/Playbook/PlaybookCard/PlaybookCard.test.js
components/Playbook/mocks.js
components/ScrollableTableWithMenu/TableRow/TableRow.js
components/admin/ProjectEdit/EditVideoModal/ModalForms/FileDataForm/FileDataForm.js
components/admin/ProjectReview/VideoProjectFiles/VideoProjectFile/VideoProjectFile.test.js
lib/__tests__/useInitialStatus.test.js
lib/__tests__/utils.test.js
lib/elastic/parser.js
lib/graphql/queries/playbook.js
lib/hooks/useInitialStatus.js
lib/utils.js

This PR handles the date and time display on playbook pages (Commons and admin preview) and playbook cards on Commons.
* Displays the time in the Eastern time zone and should automatically update for daylight saving time. I included a test for the `formatDateTime` utility function for this scenario.
* Displays either Updated or Published dates and label, per description in [CDP-2443](https://design.atlassian.net/browse/CDP-2443).
* Updates the tests for `Playbook` and `PlaybookCard` for the various scenarios.

CDP-2431: Updated all labels and timestamps on the Preview and Frontend

---

components/Playbook/Playbook.js
components/ScrollableTableWithMenu/ScrollableTableWithMenu.scss
lib/utils.js

These changes work with server [PR #67](https://github.com/IIP-Design/content-commons-server/pull/67) and API [PR #101](https://github.com/IIP-Design/cdp-public-api/pull/101), which make the file size and file type properties available on the public API response.
In the case that file size and/or file type are not returned, those values will be omitted from the additional resources item.
Also added a helper function to convert common MIME types into more approachable filetype names (i.e. `Word Document` rather than `application/vnd.openxmlformats-officedocument.wordprocessingml.document`).
Finally, includes an opportunistic change to the dashboard styling to override Semantic UI styling that was rounding the corners of the scrollable table header row.

CDP-2469: Display support file size and type properties on the playbook frontend

---

components/Playbook/Playbook.module.scss
components/admin/TextEditor/TextEditor.module.scss

This PR adjusts the styling of playbook text editor links so that content copied from Google docs appears correctly. Content copied from a Google doc wraps underlined links in a `u` tag, which prevented the previous styling from being displayed. This also addresses Google doc headings that are wrapped in `strong` tags. Because of the `strong` tag, the desired color for headings was not being displayed correctly.

Playbook text editor link style adjustments
